title: Ealaín

description: Learning Art with Krita

url: "http://dmnfarrell.github.com/digitalart/"
baseurl: "/digitalart"
paginate_path: "/page:num/"
permalink: /:day/:year/:month/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 7

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Archive
    url: /archive
  - title: Categories
    url: /categories
  - title: Gallery
    url: /gallery

social:
  github: dmnfarrell
  twitter: dmnfarrell

#google_analytics: "UA-58263416-1"
